language: android

jdk:
  - oraclejdk8

android:
  components:
    - platform-tools
    - tools
    - build-tools-24.0.2
    - android-24
    - extra-android-m2repository

addons:
  apt:
    packages:
    - libstdc++6

before_install:
  - sudo apt-get update
  - sudo apt-get upgrade
  - git clone https://github.com/urho3d/android-ndk.git $HOME/android-ndk-root
  - export ANDROID_NDK_HOME=$HOME/android-ndk-root
  - ./install-cmake.sh

before_script:
    - chmod +x gradlew

script: "./gradlew build"

sudo: required
