language: android

jdk:
  - oraclejdk8

android:
  components:
    - platform-tools
    - tools
    - build-tools-24.0.2
    - android-24
    - extra-android-m2repository

before_install:
  # By default, we get an older version of libstdc++6 so we need to update it
  - sudo apt-get update
  - sudo apt-get install -y libstdc++6
  - git clone https://github.com/urho3d/android-ndk.git $HOME/android-ndk-root
  - export ANDROID_NDK_HOME=$HOME/android-ndk-root
  - ./install-cmake.sh

before_script:
    - chmod +x gradlew

script: "./gradlew build"

sudo: required
