language: android

jdk:
  - oraclejdk8

android:
  components:
    - platform-tools
    - tools
    - build-tools-25.0.2
    - android-25
    - extra-android-m2repository

before_install:
  # By default, we get an older version of libstdc++6 so we need to update it
  # http://askubuntu.com/questions/575505/glibcxx-3-4-20-not-found-how-to-fix-this-error
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update
  - sudo apt-get install libstdc++6
  - git clone https://github.com/urho3d/android-ndk.git $HOME/android-ndk-root
  - export ANDROID_NDK_HOME=$HOME/android-ndk-root

before_script:
    - ./$ANDROID_HOME/tools/bin/sdkmanager cmake;3.6.3155560
    - chmod +x gradlew

script: "./gradlew build"

sudo: required
